version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
